# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hailo-apps"
BBFILE_PATTERN_hailo-apps = "^${LAYERDIR}/"
BBFILE_PRIORITY_hailo-apps = "8"

LAYERDEPENDS_hailo-apps = "core"
LAYERSERIES_COMPAT_hailo-apps = "scarthgap"

# Layer version
LAYERVERSION_hailo-apps = "1"
